### ISSUE TITLE
Vpn players will got fakelag together.

### ISSUE THREAD

**Issue by Target5150** [ProdigySim/custom_fakelag#3]
Asian competitive server always set vpn server for some player because of their route not good with server main IP.
But if they using same vpn ip connect to server , and set one of them fakelag , will got fakelag together.
![C4X X98G7 NCRWLD$W}4P$B](https://user-images.githubusercontent.com/42076548/105818958-7b486b00-5ff2-11eb-9acd-fb2f6447b009.png)  original ping
![image](https://user-images.githubusercontent.com/42076548/105819028-974c0c80-5ff2-11eb-8c57-b987431468e9.png)
![image](https://user-images.githubusercontent.com/42076548/105819044-9dda8400-5ff2-11eb-93f6-7d1057a0c105.png)
after set fakelag(just set on suibianihhihh)

> Format(ipString, 31, "%d.%d.%d.%d", LOBYTE(ip), LOBYTE(ip >> 8), LOBYTE(ip >> 16), LOBYTE(ip >> 24));

I guess because of IP format doesn't include the port, add it maybe deal this issue?

**Comment by ProdigySim** [comment]
Good point. I had forgotten about VPNs. I was assuming that if two players had the same IP it meant they were in the same house.

We can probably differentiate using port.
